# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/refs/heads/main/schema/markdownlint-cli2-config-schema.json

globs:
  - "{articles,books}/*.md"

config:
  single-title: false
  no-bare-urls: false
  line-length: false
